global using Carter;
global using MediatR;
global using Mapster;
global using BuildingBlocks.CQRS;
global using Catalog.API.Models;
global using Marten;
global using Microsoft.AspNetCore.Mvc;
global using FluentValidation;
global using Catalog.API.Data;
